// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/greeterDua.proto

package greeter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BarangService_AllBarang_FullMethodName = "/greeterDua.BarangService/AllBarang"
)

// BarangServiceClient is the client API for BarangService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BarangServiceClient interface {
	AllBarang(ctx context.Context, in *BarangRequest, opts ...grpc.CallOption) (*BarangReply, error)
}

type barangServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBarangServiceClient(cc grpc.ClientConnInterface) BarangServiceClient {
	return &barangServiceClient{cc}
}

func (c *barangServiceClient) AllBarang(ctx context.Context, in *BarangRequest, opts ...grpc.CallOption) (*BarangReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BarangReply)
	err := c.cc.Invoke(ctx, BarangService_AllBarang_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarangServiceServer is the server API for BarangService service.
// All implementations must embed UnimplementedBarangServiceServer
// for forward compatibility.
type BarangServiceServer interface {
	AllBarang(context.Context, *BarangRequest) (*BarangReply, error)
	mustEmbedUnimplementedBarangServiceServer()
}

// UnimplementedBarangServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBarangServiceServer struct{}

func (UnimplementedBarangServiceServer) AllBarang(context.Context, *BarangRequest) (*BarangReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllBarang not implemented")
}
func (UnimplementedBarangServiceServer) mustEmbedUnimplementedBarangServiceServer() {}
func (UnimplementedBarangServiceServer) testEmbeddedByValue()                       {}

// UnsafeBarangServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarangServiceServer will
// result in compilation errors.
type UnsafeBarangServiceServer interface {
	mustEmbedUnimplementedBarangServiceServer()
}

func RegisterBarangServiceServer(s grpc.ServiceRegistrar, srv BarangServiceServer) {
	// If the following call pancis, it indicates UnimplementedBarangServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BarangService_ServiceDesc, srv)
}

func _BarangService_AllBarang_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarangRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarangServiceServer).AllBarang(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarangService_AllBarang_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarangServiceServer).AllBarang(ctx, req.(*BarangRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BarangService_ServiceDesc is the grpc.ServiceDesc for BarangService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BarangService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greeterDua.BarangService",
	HandlerType: (*BarangServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllBarang",
			Handler:    _BarangService_AllBarang_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/greeterDua.proto",
}
